export const SITE_CONFIG = {
  company: {
    name: "RYX Dev Solutions",
    shortName: "RYX",
    siteUrl: "https://ryxtech.in",
    email: "ryxdevsolutions@gmail.com",
    whatsapp: "https://wa.me/918667258008",
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    location: "Coimbatore, India",
    founded: "2023",
    tagline: "Build & Scale",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "About us", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Contact", href: "/contact" },
  ],
  social: {
    facebook: "https://facebook.com/ryxdev",
    linkedin: "https://linkedin.com/company/ryxdev",
    twitter: "https://x.com/ryxdev",
    instagram: "https://instagram.com/ryxdev",
    github: "https://github.com/ryxdevsolution-stack",
  },
  team: [
    {
      name: "Sowmiya",
      role: "Founder & CEO",
      image: "/images/team-1.jpg",
      bio: "Leads client relationships, product strategy, and business growth. Drives every project from discovery to delivery.",
    },
    {
      name: "Ramesh",
      role: "Co-Founder & Lead Developer",
      image: "/images/team-2.jpg",
      bio: "Full-stack developer and co-founder. Builds scalable backends and frontend interfaces across all projects.",
    },
    {
      name: "Logesh",
      role: "Co-Founder & Lead Developer",
      image: "/images/team-3.jpg",
      bio: "Architected Valoryx's offline-sync system and BigTeam's backend. Leads technical delivery and project management across all builds.",
    },
  ],
  stats: [
    { value: "4", label: "Projects Delivered" },
    { value: "4", label: "Industries Served" },
    { value: "3", label: "Core Team Members" },
    { value: "2023", label: "Founded" },
  ],
  technologies: [
    "Next.js",
    "React",
    "TypeScript",
    "Python",
    "Flask",
    "PostgreSQL",
    "Supabase",
    "Tailwind CSS",
    "Electron",
    "SQLite",
  ],
} as const;
