export const SITE_CONFIG = {
  company: {
    name: "RYX Dev Solutions",
    shortName: "RYX",
    email: "ryxdevsolutions@gmail.com",
    phone: "+91 6374853277",
    whatsapp: "https://wa.me/916374853277",
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    location: "Coimbatore, India",
    founded: "2023",
    tagline: "Build & Scale",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "About us", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Contact", href: "/contact" },
  ],
  social: {
    facebook: "https://facebook.com/ryxdev",
    linkedin: "https://linkedin.com/company/ryxdev",
    twitter: "https://x.com/ryxdev",
    instagram: "https://instagram.com/ryxdev",
    github: "https://github.com/ryxdev",
  },
  team: [
    {
      name: "Sowmiya",
      role: "Founder & CEO",
      image: "/images/team-1.jpg",
      bio: "Visionary behind RYX. Drives strategy, client relationships, and product direction.",
    },
    {
      name: "Ramesh",
      role: "Co-Founder & Lead Developer",
      image: "/images/team-2.jpg",
      bio: "Full-stack architect and co-founder. Builds scalable systems and leads technical delivery.",
    },
    {
      name: "Logesh",
      role: "Co-Founder & Developer",
      image: "/images/team-3.jpg",
      bio: "Product co-founder. Shapes UX and drives frontend excellence across all projects.",
    },
  ],
  stats: [
    { value: "15+", label: "Projects Delivered" },
    { value: "98%", label: "Client Satisfaction" },
    { value: "3", label: "Core Team Members" },
    { value: "2023", label: "Founded" },
  ],
  technologies: [
    "Next.js",
    "React",
    "TypeScript",
    "Supabase",
    "React Native",
    "Figma",
    "Tailwind CSS",
    "Node.js",
  ],
} as const;
